name: Security Tests

on: [push, pull_request]

jobs:
  security-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: WaveForm_db
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install pip and pip-tools
        run: |
          python -m ensurepip --upgrade
          python -m pip install --upgrade pip
          pip install pip-tools

      - name: Generate requirements.txt
        run: |
          pip-compile tests/requirements.in

      - name: Install dependencies
        run: |
          pip install -r tests/requirements.txt

      - name: Wait for MySQL to start
        run: |
          while ! mysqladmin ping -h 127.0.0.1 --silent; do
            echo "Waiting for database connection..."
            sleep 5
          done

      - name: Run security tests
        env:
          MYSQL_HOST: 127.0.0.1
          MYSQL_USER: root
          MYSQL_PASSWORD: ""
          MYSQL_DATABASE: WaveForm_db
        run: |
          python -m unittest /tests/Automated/test_security.py

# Run all tests command below

# python -m unittest discover -s tests
