name: Security Tests

on: [push, pull_request]

jobs:
  security-tests:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install pip and pip-tools
        run: |
          python -m ensurepip --upgrade
          python -m pip install --upgrade pip
          pip install pip-tools

      - name: Generate requirements.txt
        run: |
          pip-compile tests/requirements.in

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements.txt

      - name: Run security tests
        run: |
          python -m unittest test_user_security.py
