name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
          MYSQL_DATABASE: WaveForm_db
        ports:
          - 3307:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install mysql-connector-python

      - name: Initialize database
        run: |
          mysql -h127.0.0.1 -P3307 -uroot WaveForm_db < app/db/WaveForm_db.sql

      - name: Create .env file
        run: |
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_USER=root" >> .env
          echo "DB_PASSWORD=" >> .env
          echo "DB_NAME=WaveForm_db" >> .env

      - name: Run tests
        env:
          DB_HOST: 127.0.0.1
          DB_USER: root
          DB_PASSWORD: ""
          DB_NAME: WaveForm_db
        run: |
          python -m unittest tests/Automated/test_security.py
